/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-bg-subtle": "#1c1c1c",
        "fg-text-contrast": "#ecedee",
        "fg-border-hover": "#4c5155",
        "fg-default-fg": "#fff",
        "fg-line": "#313538",
        "fg-text": "#9ba1a6",
        "secondary-bg": "#232323",
        "secondary-bg-active": "#2e2e2e",
        "secondary-text": "#a0a0a0",
        "secondary-line": "#343434",
        "secondary-solid": "#707070",
      },
      spacing: {
        "spacing-8": "32px",
        "sizing-16": "64px",
        "spacing-0": "0px",
        "screens-xl": "1280px",
        "spacing-10": "40px",
        "spacing-01": "0px",
        "spacing-2": "8px",
        "sizing-161": "64px",
        "spacing-101": "40px",
        "spacing-4": "16px",
        "spacing-6": "24px",
        "sizing-12": "48px",
        "screens-md": "768px",
        "sizing-11": "44px",
        "spacing-32": "128px",
        "spacing-9": "36px",
        "spacing-20": "80px",
        "screens-lg": "1024px",
        "screens-lg1": "1024px",
        "spacing-3": "12px",
        "spacing-02": "0px",
        "spacing-35": "14px",
        "screens-sm": "640px",
        "spacing-16": "64px",
        "screens-md1": "768px",
        "spacing-161": "64px",
        "spacing-12": "48px",
        "spacing-81": "32px",
        "spacing-61": "24px",
        "spacing-5": "20px",
        "spacing-41": "16px",
        "spacing-21": "8px",
        "spacing-03": "0px",
        "spacing-82": "32px",
        "spacing-22": "8px",
        "sizing-80": "320px",
        "sizing-121": "48px",
        "screens-xl1": "1280px",
        "spacing-14": "56px",
        "spacing-42": "16px",
        "spacing-23": "8px",
      },
      borderRadius: {
        "borderradius-rounded-3xl": "24px",
        "borderradius-rounded-full": "9999px",
        "borderradius-rounded-2xl": "16px",
        "borderradius-rounded-md": "6px",
        "borderradius-rounded-xl": "12px",
        "borderradius-rounded-2xl1": "16px",
        "borderradius-rounded-3xl1": "24px",
      },
    },
    screens: {},
  },
  corePlugins: {
    preflight: false,
  },
};
